# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(885, 698)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setStyleSheet("color:rgb(42, 42, 42)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("color:rgb(0, 49, 36)")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.drop_shadow_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: rgb(0, 27, 39);\n"
"border-radius: 10px;\n"
"")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.drop_shadow_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_bar = QtWidgets.QFrame(parent=self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color: none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(parent=self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_title = QtWidgets.QLabel(parent=self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(500, 32))
        self.label_title.setMaximumSize(QtCore.QSize(9999999, 9999999))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Cambria\";")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.label_padNotDetected = QtWidgets.QLabel(parent=self.frame_title)
        self.label_padNotDetected.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_padNotDetected.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_padNotDetected.setObjectName("label_padNotDetected")
        self.horizontalLayout_2.addWidget(self.label_padNotDetected)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_connectionNotDetected = QtWidgets.QLabel(parent=self.frame_title)
        self.label_connectionNotDetected.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_connectionNotDetected.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_connectionNotDetected.setObjectName("label_connectionNotDetected")
        self.horizontalLayout_2.addWidget(self.label_connectionNotDetected)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(parent=self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_minimize = QtWidgets.QPushButton(parent=self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-image: url(:/icons/icons/icon_minimize.png);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"QPushButton:hover {    \n"
"    \n"
"    background-color: rgb(91, 91, 91);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(parent=self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        self.btn_maximize.setFont(font)
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-image: url(:/icons/icons/icon_maximize.png);\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(91, 91, 91);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_3.addWidget(self.btn_maximize)
        self.btn_restore = QtWidgets.QPushButton(parent=self.frame_btns)
        self.btn_restore.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_restore.setMaximumSize(QtCore.QSize(17, 17))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        self.btn_restore.setFont(font)
        self.btn_restore.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-image: url(:/icons/icons/icon_maximize.png);\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(91, 91, 91);\n"
"}")
        self.btn_restore.setText("")
        self.btn_restore.setObjectName("btn_restore")
        self.horizontalLayout_3.addWidget(self.btn_restore)
        self.btn_close = QtWidgets.QPushButton(parent=self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(221, 114, 21);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-image: url(:/icons/icons/icon_close.png);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgb(159, 80, 15);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.gridLayout_2.addWidget(self.title_bar, 0, 0, 1, 1)
        self.content_bar_and_styleSheet = QtWidgets.QFrame(parent=self.drop_shadow_frame)
        self.content_bar_and_styleSheet.setStyleSheet("/*  ///////////////////////////////////////////////////// Check Box */\n"
"\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(221, 114, 21);\n"
"    border: 3px solid rgb(159, 80, 15);    \n"
"    background-image: url(:/icons/icons/cil-check-alt.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"QCheckBox {\n"
"    background-color: none;\n"
"    color: rgb(222, 225, 229);\n"
"}\n"
"\n"
"/* ///////////////////////////////////// Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(221, 114, 21);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(159, 80, 15);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(144, 72, 14);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(221, 114, 21);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(159, 80, 15);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(144, 72, 14);\n"
"}\n"
"QSlider {\n"
"    background-color: none;\n"
"}\n"
"\n"
"/* Frame */\n"
"QFrame{\n"
"    background-color:none;\n"
"}\n"
"\n"
"/*  Label */\n"
"QLabel {\n"
"    color: rgb(222, 225, 229);\n"
"}\n"
"\n"
"/* The content_bar itself */\n"
"background-color: none;")
        self.content_bar_and_styleSheet.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content_bar_and_styleSheet.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content_bar_and_styleSheet.setObjectName("content_bar_and_styleSheet")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.content_bar_and_styleSheet)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dashboard_frame = QtWidgets.QFrame(parent=self.content_bar_and_styleSheet)
        self.dashboard_frame.setStyleSheet("background-color: rgb(0, 27, 39);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.dashboard_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dashboard_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dashboard_frame.setObjectName("dashboard_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dashboard_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.camera_feed = QtWidgets.QLabel(parent=self.dashboard_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_feed.sizePolicy().hasHeightForWidth())
        self.camera_feed.setSizePolicy(sizePolicy)
        self.camera_feed.setText("")
        self.camera_feed.setObjectName("camera_feed")
        self.horizontalLayout_5.addWidget(self.camera_feed)
        self.sideBar_frame = QtWidgets.QFrame(parent=self.dashboard_frame)
        self.sideBar_frame.setMaximumSize(QtCore.QSize(167, 16777215))
        self.sideBar_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sideBar_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sideBar_frame.setObjectName("sideBar_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.sideBar_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.info_stackedWidget = QtWidgets.QStackedWidget(parent=self.sideBar_frame)
        self.info_stackedWidget.setMaximumSize(QtCore.QSize(167, 16777215))
        self.info_stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_stackedWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.info_stackedWidget.setObjectName("info_stackedWidget")
        self.info_Page = QtWidgets.QWidget()
        self.info_Page.setObjectName("info_Page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.info_Page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_packetForSending = QtWidgets.QLabel(parent=self.info_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_packetForSending.sizePolicy().hasHeightForWidth())
        self.label_packetForSending.setSizePolicy(sizePolicy)
        self.label_packetForSending.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_packetForSending.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_packetForSending.setObjectName("label_packetForSending")
        self.verticalLayout.addWidget(self.label_packetForSending)
        self.packet = QtWidgets.QFrame(parent=self.info_Page)
        self.packet.setMinimumSize(QtCore.QSize(0, 171))
        self.packet.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.packet.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.packet.setObjectName("packet")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.packet)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.packet_labels = QtWidgets.QFrame(parent=self.packet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packet_labels.sizePolicy().hasHeightForWidth())
        self.packet_labels.setSizePolicy(sizePolicy)
        self.packet_labels.setMinimumSize(QtCore.QSize(100, 0))
        self.packet_labels.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.packet_labels.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.packet_labels.setObjectName("packet_labels")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.packet_labels)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.thrus_vert_0 = QtWidgets.QLabel(parent=self.packet_labels)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 27, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.thrus_vert_0.setPalette(palette)
        self.thrus_vert_0.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_vert_0.setObjectName("thrus_vert_0")
        self.verticalLayout_2.addWidget(self.thrus_vert_0)
        self.thrus_vert_1 = QtWidgets.QLabel(parent=self.packet_labels)
        self.thrus_vert_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_vert_1.setObjectName("thrus_vert_1")
        self.verticalLayout_2.addWidget(self.thrus_vert_1)
        self.thrus_horiz_0 = QtWidgets.QLabel(parent=self.packet_labels)
        self.thrus_horiz_0.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_0.setObjectName("thrus_horiz_0")
        self.verticalLayout_2.addWidget(self.thrus_horiz_0)
        self.thrus_horiz_1 = QtWidgets.QLabel(parent=self.packet_labels)
        self.thrus_horiz_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_1.setObjectName("thrus_horiz_1")
        self.verticalLayout_2.addWidget(self.thrus_horiz_1)
        self.thrus_horiz_2 = QtWidgets.QLabel(parent=self.packet_labels)
        self.thrus_horiz_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_2.setObjectName("thrus_horiz_2")
        self.verticalLayout_2.addWidget(self.thrus_horiz_2)
        self.thrus_horiz_3 = QtWidgets.QLabel(parent=self.packet_labels)
        self.thrus_horiz_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_3.setObjectName("thrus_horiz_3")
        self.verticalLayout_2.addWidget(self.thrus_horiz_3)
        self.manip_rotation = QtWidgets.QLabel(parent=self.packet_labels)
        self.manip_rotation.setStyleSheet("color: rgb(255, 255, 255);")
        self.manip_rotation.setObjectName("manip_rotation")
        self.verticalLayout_2.addWidget(self.manip_rotation)
        self.manip_grabber = QtWidgets.QLabel(parent=self.packet_labels)
        self.manip_grabber.setStyleSheet("color: rgb(255, 255, 255);")
        self.manip_grabber.setObjectName("manip_grabber")
        self.verticalLayout_2.addWidget(self.manip_grabber)
        self.horizontalLayout_6.addWidget(self.packet_labels)
        self.packet_values = QtWidgets.QFrame(parent=self.packet)
        self.packet_values.setMaximumSize(QtCore.QSize(35, 16777215))
        self.packet_values.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.packet_values.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.packet_values.setObjectName("packet_values")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.packet_values)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.thrus_vert_0_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.thrus_vert_0_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_vert_0_perc.setObjectName("thrus_vert_0_perc")
        self.verticalLayout_3.addWidget(self.thrus_vert_0_perc)
        self.thrus_vert_1_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.thrus_vert_1_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_vert_1_perc.setObjectName("thrus_vert_1_perc")
        self.verticalLayout_3.addWidget(self.thrus_vert_1_perc)
        self.thrus_horiz_0_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.thrus_horiz_0_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_0_perc.setObjectName("thrus_horiz_0_perc")
        self.verticalLayout_3.addWidget(self.thrus_horiz_0_perc)
        self.thrus_horiz_1_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.thrus_horiz_1_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_1_perc.setObjectName("thrus_horiz_1_perc")
        self.verticalLayout_3.addWidget(self.thrus_horiz_1_perc)
        self.thrus_horiz_2_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.thrus_horiz_2_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_2_perc.setObjectName("thrus_horiz_2_perc")
        self.verticalLayout_3.addWidget(self.thrus_horiz_2_perc)
        self.thrus_horiz_3_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.thrus_horiz_3_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.thrus_horiz_3_perc.setObjectName("thrus_horiz_3_perc")
        self.verticalLayout_3.addWidget(self.thrus_horiz_3_perc)
        self.manip_rotation_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.manip_rotation_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.manip_rotation_perc.setObjectName("manip_rotation_perc")
        self.verticalLayout_3.addWidget(self.manip_rotation_perc)
        self.manip_grabber_perc = QtWidgets.QLabel(parent=self.packet_values)
        self.manip_grabber_perc.setMinimumSize(QtCore.QSize(30, 0))
        self.manip_grabber_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.manip_grabber_perc.setObjectName("manip_grabber_perc")
        self.verticalLayout_3.addWidget(self.manip_grabber_perc)
        self.horizontalLayout_6.addWidget(self.packet_values)
        self.verticalLayout.addWidget(self.packet)
        self.label_telemetry = QtWidgets.QLabel(parent=self.info_Page)
        self.label_telemetry.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_telemetry.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_telemetry.setObjectName("label_telemetry")
        self.verticalLayout.addWidget(self.label_telemetry)
        self.telemetry_angles = QtWidgets.QFrame(parent=self.info_Page)
        self.telemetry_angles.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.telemetry_angles.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.telemetry_angles.setObjectName("telemetry_angles")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.telemetry_angles)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.telemetry_labels = QtWidgets.QFrame(parent=self.telemetry_angles)
        self.telemetry_labels.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.telemetry_labels.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.telemetry_labels.setObjectName("telemetry_labels")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.telemetry_labels)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pitch_label = QtWidgets.QLabel(parent=self.telemetry_labels)
        self.pitch_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.pitch_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pitch_label.setObjectName("pitch_label")
        self.verticalLayout_8.addWidget(self.pitch_label)
        self.roll_label = QtWidgets.QLabel(parent=self.telemetry_labels)
        self.roll_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.roll_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roll_label.setObjectName("roll_label")
        self.verticalLayout_8.addWidget(self.roll_label)
        self.yaw_label = QtWidgets.QLabel(parent=self.telemetry_labels)
        self.yaw_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.yaw_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yaw_label.setObjectName("yaw_label")
        self.verticalLayout_8.addWidget(self.yaw_label)
        self.horizontalLayout_8.addWidget(self.telemetry_labels)
        self.telemetry_digits = QtWidgets.QFrame(parent=self.telemetry_angles)
        self.telemetry_digits.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.telemetry_digits.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.telemetry_digits.setObjectName("telemetry_digits")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.telemetry_digits)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pitch_digit = QtWidgets.QLabel(parent=self.telemetry_digits)
        self.pitch_digit.setStyleSheet("color: rgb(255, 255, 255);")
        self.pitch_digit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pitch_digit.setObjectName("pitch_digit")
        self.verticalLayout_7.addWidget(self.pitch_digit)
        self.roll_digit = QtWidgets.QLabel(parent=self.telemetry_digits)
        self.roll_digit.setStyleSheet("color: rgb(255, 255, 255);")
        self.roll_digit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roll_digit.setObjectName("roll_digit")
        self.verticalLayout_7.addWidget(self.roll_digit)
        self.yaw_digit = QtWidgets.QLabel(parent=self.telemetry_digits)
        self.yaw_digit.setStyleSheet("color: rgb(255, 255, 255);")
        self.yaw_digit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yaw_digit.setObjectName("yaw_digit")
        self.verticalLayout_7.addWidget(self.yaw_digit)
        self.horizontalLayout_8.addWidget(self.telemetry_digits)
        self.verticalLayout.addWidget(self.telemetry_angles)
        self.label_inputs = QtWidgets.QLabel(parent=self.info_Page)
        self.label_inputs.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_inputs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_inputs.setObjectName("label_inputs")
        self.verticalLayout.addWidget(self.label_inputs)
        self.bidjo = QtWidgets.QFrame(parent=self.info_Page)
        self.bidjo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bidjo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bidjo.setObjectName("bidjo")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.bidjo)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttons_labels_perc = QtWidgets.QFrame(parent=self.bidjo)
        self.buttons_labels_perc.setMinimumSize(QtCore.QSize(0, 160))
        self.buttons_labels_perc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttons_labels_perc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttons_labels_perc.setObjectName("buttons_labels_perc")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.buttons_labels_perc)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.buttons_labels = QtWidgets.QFrame(parent=self.buttons_labels_perc)
        self.buttons_labels.setStyleSheet("color: rgb(255, 255, 255);")
        self.buttons_labels.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttons_labels.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttons_labels.setObjectName("buttons_labels")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.buttons_labels)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonY = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonY.setObjectName("buttonY")
        self.verticalLayout_4.addWidget(self.buttonY)
        self.buttonB = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonB.setObjectName("buttonB")
        self.verticalLayout_4.addWidget(self.buttonB)
        self.buttonA = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonA.setObjectName("buttonA")
        self.verticalLayout_4.addWidget(self.buttonA)
        self.buttonX = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonX.setObjectName("buttonX")
        self.verticalLayout_4.addWidget(self.buttonX)
        self.buttonLB = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonLB.setObjectName("buttonLB")
        self.verticalLayout_4.addWidget(self.buttonLB)
        self.buttonRB = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonRB.setObjectName("buttonRB")
        self.verticalLayout_4.addWidget(self.buttonRB)
        self.buttonLT = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonLT.setObjectName("buttonLT")
        self.verticalLayout_4.addWidget(self.buttonLT)
        self.buttonRT = QtWidgets.QLabel(parent=self.buttons_labels)
        self.buttonRT.setObjectName("buttonRT")
        self.verticalLayout_4.addWidget(self.buttonRT)
        self.horizontalLayout_10.addWidget(self.buttons_labels)
        self.inputs_perc = QtWidgets.QFrame(parent=self.buttons_labels_perc)
        self.inputs_perc.setStyleSheet("color: rgb(255, 255, 255);")
        self.inputs_perc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.inputs_perc.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.inputs_perc.setObjectName("inputs_perc")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inputs_perc)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.buttonY_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonY_perc.setObjectName("buttonY_perc")
        self.verticalLayout_5.addWidget(self.buttonY_perc)
        self.buttonB_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonB_perc.setObjectName("buttonB_perc")
        self.verticalLayout_5.addWidget(self.buttonB_perc)
        self.buttonA_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonA_perc.setObjectName("buttonA_perc")
        self.verticalLayout_5.addWidget(self.buttonA_perc)
        self.buttonX_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonX_perc.setObjectName("buttonX_perc")
        self.verticalLayout_5.addWidget(self.buttonX_perc)
        self.buttonLB_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonLB_perc.setObjectName("buttonLB_perc")
        self.verticalLayout_5.addWidget(self.buttonLB_perc)
        self.buttonRB_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonRB_perc.setObjectName("buttonRB_perc")
        self.verticalLayout_5.addWidget(self.buttonRB_perc)
        self.buttonLT_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonLT_perc.setObjectName("buttonLT_perc")
        self.verticalLayout_5.addWidget(self.buttonLT_perc)
        self.buttonRT_perc = QtWidgets.QLabel(parent=self.inputs_perc)
        self.buttonRT_perc.setObjectName("buttonRT_perc")
        self.verticalLayout_5.addWidget(self.buttonRT_perc)
        self.horizontalLayout_10.addWidget(self.inputs_perc)
        self.horizontalLayout_7.addWidget(self.buttons_labels_perc)
        self.verticalLayout.addWidget(self.bidjo)
        self.info_stackedWidget.addWidget(self.info_Page)
        self.PID_Page = QtWidgets.QWidget()
        self.PID_Page.setObjectName("PID_Page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PID_Page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pid_home = QtWidgets.QFrame(parent=self.PID_Page)
        self.pid_home.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pid_home.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pid_home.setObjectName("pid_home")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pid_home)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_title_controls = QtWidgets.QLabel(parent=self.pid_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_controls.sizePolicy().hasHeightForWidth())
        self.label_title_controls.setSizePolicy(sizePolicy)
        self.label_title_controls.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title_controls.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title_controls.setObjectName("label_title_controls")
        self.verticalLayout_11.addWidget(self.label_title_controls)
        self.frame_coefs = QtWidgets.QFrame(parent=self.pid_home)
        self.frame_coefs.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_coefs.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_coefs.setObjectName("frame_coefs")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_coefs)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_coefs_labels = QtWidgets.QFrame(parent=self.frame_coefs)
        self.frame_coefs_labels.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_coefs_labels.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_coefs_labels.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_coefs_labels.setObjectName("frame_coefs_labels")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_coefs_labels)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.P_label = QtWidgets.QLabel(parent=self.frame_coefs_labels)
        self.P_label.setObjectName("P_label")
        self.verticalLayout_12.addWidget(self.P_label)
        self.i_label = QtWidgets.QLabel(parent=self.frame_coefs_labels)
        self.i_label.setObjectName("i_label")
        self.verticalLayout_12.addWidget(self.i_label)
        self.D_label = QtWidgets.QLabel(parent=self.frame_coefs_labels)
        self.D_label.setObjectName("D_label")
        self.verticalLayout_12.addWidget(self.D_label)
        self.depth_label = QtWidgets.QLabel(parent=self.frame_coefs_labels)
        self.depth_label.setObjectName("depth_label")
        self.verticalLayout_12.addWidget(self.depth_label)
        self.heading_label = QtWidgets.QLabel(parent=self.frame_coefs_labels)
        self.heading_label.setObjectName("heading_label")
        self.verticalLayout_12.addWidget(self.heading_label)
        self.horizontalLayout_11.addWidget(self.frame_coefs_labels)
        self.frame_coefs_fields = QtWidgets.QFrame(parent=self.frame_coefs)
        self.frame_coefs_fields.setMinimumSize(QtCore.QSize(42, 0))
        self.frame_coefs_fields.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_coefs_fields.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_coefs_fields.setObjectName("frame_coefs_fields")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_coefs_fields)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.P_coef_field = QtWidgets.QLineEdit(parent=self.frame_coefs_fields)
        self.P_coef_field.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"color: rgb(255, 255, 255);")
        self.P_coef_field.setObjectName("P_coef_field")
        self.verticalLayout_13.addWidget(self.P_coef_field)
        self.I_coef_field = QtWidgets.QLineEdit(parent=self.frame_coefs_fields)
        self.I_coef_field.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"color: rgb(255, 255, 255);")
        self.I_coef_field.setObjectName("I_coef_field")
        self.verticalLayout_13.addWidget(self.I_coef_field)
        self.D_coef_field = QtWidgets.QLineEdit(parent=self.frame_coefs_fields)
        self.D_coef_field.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"color: rgb(255, 255, 255);")
        self.D_coef_field.setObjectName("D_coef_field")
        self.verticalLayout_13.addWidget(self.D_coef_field)
        self.depth_coef_field = QtWidgets.QLineEdit(parent=self.frame_coefs_fields)
        self.depth_coef_field.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"color: rgb(255, 255, 255);")
        self.depth_coef_field.setObjectName("depth_coef_field")
        self.verticalLayout_13.addWidget(self.depth_coef_field)
        self.heading_coef_field = QtWidgets.QLineEdit(parent=self.frame_coefs_fields)
        self.heading_coef_field.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"color: rgb(255, 255, 255);")
        self.heading_coef_field.setObjectName("heading_coef_field")
        self.verticalLayout_13.addWidget(self.heading_coef_field)
        self.horizontalLayout_11.addWidget(self.frame_coefs_fields)
        self.verticalLayout_11.addWidget(self.frame_coefs)
        self.buttonSubmitCoefs = QtWidgets.QPushButton(parent=self.pid_home)
        self.buttonSubmitCoefs.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 44, 44);\n"
"border-radius: 40px;                     /* <----  20px  */ ")
        self.buttonSubmitCoefs.setObjectName("buttonSubmitCoefs")
        self.verticalLayout_11.addWidget(self.buttonSubmitCoefs)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.verticalLayout_9.addWidget(self.pid_home)
        self.info_stackedWidget.addWidget(self.PID_Page)
        self.verticalLayout_10.addWidget(self.info_stackedWidget)
        self.frame = QtWidgets.QFrame(parent=self.sideBar_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_controlsTab = QtWidgets.QPushButton(parent=self.frame)
        self.button_controlsTab.setMinimumSize(QtCore.QSize(0, 50))
        self.button_controlsTab.setStyleSheet("color: rgb(255, 255, 255);\n"
"image: url(:/icons/pngs_to_include/USB-Gamepad-Transparent.png);")
        self.button_controlsTab.setText("")
        self.button_controlsTab.setObjectName("button_controlsTab")
        self.horizontalLayout_4.addWidget(self.button_controlsTab)
        self.button_tauTab = QtWidgets.QPushButton(parent=self.frame)
        self.button_tauTab.setMinimumSize(QtCore.QSize(0, 70))
        self.button_tauTab.setStyleSheet("color: rgb(255, 255, 255);\n"
"image: url(:/icons/pngs_to_include/DataGuru_ICON-white-1.png);")
        self.button_tauTab.setText("")
        self.button_tauTab.setObjectName("button_tauTab")
        self.horizontalLayout_4.addWidget(self.button_tauTab)
        self.verticalLayout_10.addWidget(self.frame)
        self.horizontalLayout_5.addWidget(self.sideBar_frame)
        self.verticalLayout_6.addWidget(self.dashboard_frame)
        self.gridLayout_2.addWidget(self.content_bar_and_styleSheet, 1, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.info_stackedWidget.setCurrentIndex(1)
        self.btn_minimize.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.btn_maximize.clicked.connect(MainWindow.showFullScreen) # type: ignore
        self.btn_restore.clicked.connect(MainWindow.showNormal) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "ROV CONTROL"))
        self.label_padNotDetected.setText(_translate("MainWindow", "Нет геймпада"))
        self.label_connectionNotDetected.setText(_translate("MainWindow", "Нет аппарата"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_restore.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.label_packetForSending.setText(_translate("MainWindow", "Пакет к отправке:"))
        self.thrus_vert_0.setText(_translate("MainWindow", "Верт_0"))
        self.thrus_vert_1.setText(_translate("MainWindow", "Верт_1"))
        self.thrus_horiz_0.setText(_translate("MainWindow", "Гориз_0"))
        self.thrus_horiz_1.setText(_translate("MainWindow", "Гориз_1"))
        self.thrus_horiz_2.setText(_translate("MainWindow", "Гориз_2"))
        self.thrus_horiz_3.setText(_translate("MainWindow", "Гориз_3"))
        self.manip_rotation.setText(_translate("MainWindow", "Ман_Вращ"))
        self.manip_grabber.setText(_translate("MainWindow", "Ман_Сжат"))
        self.thrus_vert_0_perc.setText(_translate("MainWindow", "0%"))
        self.thrus_vert_1_perc.setText(_translate("MainWindow", "0%"))
        self.thrus_horiz_0_perc.setText(_translate("MainWindow", "0%"))
        self.thrus_horiz_1_perc.setText(_translate("MainWindow", "0%"))
        self.thrus_horiz_2_perc.setText(_translate("MainWindow", "0%"))
        self.thrus_horiz_3_perc.setText(_translate("MainWindow", "0%"))
        self.manip_rotation_perc.setText(_translate("MainWindow", "0%"))
        self.manip_grabber_perc.setText(_translate("MainWindow", "0%"))
        self.label_telemetry.setText(_translate("MainWindow", "Телеметрия: "))
        self.pitch_label.setText(_translate("MainWindow", "Тангаж:"))
        self.roll_label.setText(_translate("MainWindow", "Крен:"))
        self.yaw_label.setText(_translate("MainWindow", "Рыскание"))
        self.pitch_digit.setText(_translate("MainWindow", "0"))
        self.roll_digit.setText(_translate("MainWindow", "0"))
        self.yaw_digit.setText(_translate("MainWindow", "0"))
        self.label_inputs.setText(_translate("MainWindow", "Ввод:"))
        self.buttonY.setText(_translate("MainWindow", "Y"))
        self.buttonB.setText(_translate("MainWindow", "B"))
        self.buttonA.setText(_translate("MainWindow", "A"))
        self.buttonX.setText(_translate("MainWindow", "X"))
        self.buttonLB.setText(_translate("MainWindow", "LB"))
        self.buttonRB.setText(_translate("MainWindow", "RB"))
        self.buttonLT.setText(_translate("MainWindow", "LT"))
        self.buttonRT.setText(_translate("MainWindow", "RT"))
        self.buttonY_perc.setText(_translate("MainWindow", "0%"))
        self.buttonB_perc.setText(_translate("MainWindow", "0%"))
        self.buttonA_perc.setText(_translate("MainWindow", "0%"))
        self.buttonX_perc.setText(_translate("MainWindow", "0%"))
        self.buttonLB_perc.setText(_translate("MainWindow", "0%"))
        self.buttonRB_perc.setText(_translate("MainWindow", "0%"))
        self.buttonLT_perc.setText(_translate("MainWindow", "0%"))
        self.buttonRT_perc.setText(_translate("MainWindow", "0%"))
        self.label_title_controls.setText(_translate("MainWindow", "Управление"))
        self.P_label.setText(_translate("MainWindow", "П"))
        self.i_label.setText(_translate("MainWindow", "И"))
        self.D_label.setText(_translate("MainWindow", "Д"))
        self.depth_label.setText(_translate("MainWindow", "Глубина"))
        self.heading_label.setText(_translate("MainWindow", "Курс"))
        self.buttonSubmitCoefs.setText(_translate("MainWindow", "Задать коэфы"))
